### ISSUE TITLE
Make  IPTV Simple play PS Vue Stream directly

### ISSUE THREAD

**Issue by eracknaphobia** [eracknaphobia/service.psvue.epg#3]
**Problem: Stream fails to play / open when directly passed**
Change the cherrypy.response.headers['Location'] to epg_play_stream(params) and have it return the ps vue stream url instead of the hardcoded one.
 
`cherrypy.response.headers['Location'] = epg_play_stream(params)`

- This would retain EPG data for the on-screen display.  
- We may not be able to use inputstream adaptive with this method.

https://github.com/eracknaphobia/service.psvue.epg/blob/950a555942317e8304baf8382bec4c1b590565ce/resources/lib/webservice.py#L95

**Comment by snoopyjoe** [comment]
I was looking at this last night. I'll play around with it.

**Comment by DiR3Wolf** [comment]
In my humble opinion, I found what I think it is a better/easier way to go about it, ditching cherrypy altogether. Please take a look at https://github.com/primaeval/plugin.video.pvr.plugin.player  from primaeval. It allows iptv simple to play each channel directly from any installed video addon. I imported  the psvue epg.xml from PSVue to test it, I was able to link PSVue addon and it works great on Kodi 18. Of course it is missing the logo, epg info etc, because it is not coded. So the idea would be to take this methology as a template, but strip it and make it work exclusively for PS Vue so it auto generates the playing link. I'll play around some more, but unfortunately, this is beyond my primitive python knowledge.

**Comment by eracknaphobia** [comment]
I was also pointed towards this [pure python pvr](https://github.com/RunasSudo/pvr.python) by Lunatixz. It may need some updates in order to work.
Another option is to use the[ uEPG addon](https://forum.kodi.tv/showthread.php?tid=321231)

**Comment by DiR3Wolf** [comment]
@eracknaphobia you are right, it doesn't fix the problem the underlying issue. However, it does look as it is simpler than cherrypy, doesn't it (at least performance wise)?

BTW, the code for uEPG addon seems to be missing, couldn't find it on Lunatixz's GitHub.

**Comment by eracknaphobia** [comment]
@DiR3Wolf Yeah, I agree it would be better to get away from cherrypy. 

I see that uEPG links are dead now... not sure if that's on purpose or not?

**Comment by DiR3Wolf** [comment]
@eracknaphobia , if I switch the code to:
 `cherrypy.response.headers['Location'] = epg_play_stream(params)` as suggested, I can still play the stream, but I get an error dialog, which you can dismiss but it is annoying. No EPG info is passed. The Kodi player doesn't identify it as a live tv type.

**Comment by eracknaphobia** [comment]
Sounds like the epg_play_stream still has the xbmc.player.play() command in it. That would be the only way it is able to play. The error message is from iptv simple not being able to resolve the location into a playable stream. That's why I had to send it a dummy stream, to quite the unplayable message and then play the stream on my own behind the scences. My idea was to have epg_play_stream return a url to iptv  simple and have it play, but it doesn't seem to pass on cookies and user-agent fwiw. Currently I'm in the process of replacing cherrypy with a much lighter approach. Hope to have more progress on stream-lining the play back after that.

**Comment by DiR3Wolf** [comment]
Got it. I also have some thoughts about EPG data gathering, but I don't want to hijack this issue thread as it is about playing the stream. Can I open an issue for discussion rather than going through the forum?

**Comment by eracknaphobia** [comment]
Sure, I would prefer that as we can better keep to a single topic.

**Comment by eracknaphobia** [comment]
Got it to redirect properly in this [commit](https://github.com/eracknaphobia/service.psvue.epg/commit/79ab04a8cf1a56efa4cf7fe3579ee11586ad7478).

**Comment by snoopyjoe** [comment]
Finally got around to reading all your comments. Cherrypy does have a few issues especially in Kodi v18. Your new code eracknaphobia is pretty solid, but like you said if using v18 then it will not take advantage of inputstream. Though hls and ffmpeg on the latest nightlies are getting better. What other alternatives to CherryPy in Kodi are there?

**Comment by DiR3Wolf** [comment]
Adding to what @snoopyjoe said, it is working well so far in Kodi 18 (as far as playback and EPG staying on). Of course, no inputstream and channel playback/switching is super slow.

**Comment by DiR3Wolf** [comment]
@eracknaphobia I wonder if this is of any relevance. It was added after on inputstream 2.2.14 https://github.com/peak3d/inputstream.adaptive/commit/c90a3783a4a8022c7d0b41c4c701c44d0e2e809b

**Comment by eracknaphobia** [comment]
Closing as this issue seems to have been solved, for Kodi 18 anyway.
