### ISSUE TITLE
17.6 issues

### ISSUE THREAD

**Issue by snoopyjoe** [eracknaphobia/service.psvue.epg#32]
There are a few issues with the service in v17. All I believe are due to the socket server code. I'm not sure what changed in Kodi but my test box gets Erron 98: Address already in use, line 149 in webservice.py. Some people are getting the 404 error as well.

I tried using different ports and localhost address but no change. If anyone else has issues with the service on 17.6 post them here so it can be narrowed down.

**Comment by eracknaphobia** [comment]
I'm seeing this issue too on 18.

**Comment by snoopyjoe** [comment]
So after the latest Kodi 18 build, 6/8/18, the service still works but the stream is unable to play. The only I see i the log file is...
ERROR: 127.0.0.1 - - [09/Jun/2018 00:34:30] "GET /psvue?params=https%3A//media-framework.totsuko.tv/media-framework/media/v2.1/stream/channel/10510 HTTP/1.1" 303

The channel URL and the stream URL look fine but when the Server is having issues either passing or parsing the URL from the uri.

**Comment by DiR3Wolf** [comment]
@snoopyjoe I just added a new issue because I saw this one called 17.6, and since I'm using 18, I ignored it. Basically, I'm having the same issue, same error. I reverted back to nightly 5/12 and it works again. Not sure what specific change is creating the problem.
